version: 2.1

jobs:
  # Job untuk linting Dockerfile menggunakan Hadolint
  lint-dockerfile:
    docker:
      - image: hadolint/hadolint:latest
    steps:
      - checkout
      - run:
          name: Lint Dockerfile
          command: hadolint Dockerfile

  # Job untuk menjalankan unit test aplikasi backend (Go)
  test-backend:
    docker:
      - image: golang:1.16
    steps:
      - checkout
      - run:
          name: Install Dependencies and Run Tests
          command: |
            go mod tidy
            go test -v -short --count=1 $(go list ./...)

  # Job untuk membangun dan mengunggah Docker image untuk backend
  build-push-backend:
  docker:
    - image: docker:latest
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Build and Push Backend Image
        command: |
          chmod +x build_push_image_karsajobs.sh
          ./build_push_image_karsajobs.sh
        environment:
          GITHUB_USERNAME: << pipeline.parameters.github_username >>
          PASSWORD_DOCKER_HUB: << pipeline.parameters.password_docker_hub >>

workflows:
  build_and_test:
    jobs:
      - lint-dockerfile
      - test-backend:
          requires:
            - lint-dockerfile
      - build-push-backend:
          requires:
            - test-backend

parameters:
  github_username:
    type: string
    default: "<< env.GITHUB_USERNAME >>"
  password_docker_hub:
    type: string
    default: "<< env.PASSWORD_DOCKER_HUB >>"